In [159]:
#Aufgabe 1.1.
import numpy as np
import pandas as pd

listings = pd.read_csv("Daten/listings_berlin.csv")

print(f"Anzahl Zeilen: {len(listings)} \nAnzahl Spalten: {len(listings.columns)}")

Anzahl_NAs = listings.isna().sum()
Anteil_NAs = listings.isna().mean().map("{:.2%}".format)

df_1_1 = pd.DataFrame({"Anzahl NAs":Anzahl_NAs, "Anteil NAs":Anteil_NAs})
df_1_1.head(20)

Anzahl Zeilen: 14274
Anzahl Spalten: 20

                           Anzahl NAs Anteil NAs
price                            5010     35.10%
neighbourhood_cleansed              0      0.00%
latitude                            0      0.00%
longitude                           0      0.00%
room_type                           0      0.00%
bedrooms                         2024     14.18%
bathrooms_text                     16      0.11%
accommodates                        0      0.00%
amenities                           0      0.00%
host_since                         14      0.10%
host_is_superhost                 164      1.15%
host_listings_count                14      0.10%
host_response_rate               5018     35.15%
review_scores_rating             3314     23.22%
review_scores_cleanliness        3314     23.22%
number_of_reviews                   0      0.00%
reviews_per_month                3314     23.22%
minimum_nights                      0      0.00%
availability_365                    0      0.00%
instant_bookable                    0      0.00%

In [160]:
#Aufagbe 1.2
#Die Tabelle aus Aufgabe 1_1 wird nach den Werten in Spalte "Anteil NAs" in "descending"-order sortiert. 
#Es werden nur die obersten drei Werte angezeigt. 
print("Die folgenden drei Werte haben die höchste Rate an fehlenden Werten:")
df_1_1.sort_values("Anteil NAs", ascending=False).head(3)

Die folgenden drei Werte haben die höchste Rate an fehlenden Werten:

                    Anzahl NAs Anteil NAs
host_response_rate        5018     35.15%
price                     5010     35.10%
reviews_per_month         3314     23.22%

placeholder für den Rest von Aufgabe 1_2

In [161]:
#Aufgabe 1_3
#Funktion wird definiert, um string-Einträge in numbers-Einträge umzuwandeln.
def clean_price(price_str):
    if type(price_str) == str:
        price_str_clean = str(price_str).replace("$", "").replace(',', '')
        print(price_str_clean, type(price_str_clean))
        try:
            price_number = pd.to_numeric(price_str_clean, dtype=float, errors="coerce")
            if price_number == 0:
                price_number = np.nan
            return price_number
        except TypeError:
             print(f"Error: There has been a faulty entry: {price_str_clean}")
    elif type(price_str) == int:
        price_number = float(price_str)
        if price_number == 0:
                price_number = np.nan
        return price_number
    elif type(price_str) == float:
        return price_str    
    else:
        print(f"Error: {price_str} was neither a string nor a number!")
        
#Die Funktion wurde abgesichert gegenüber strings, die unerwartete Zeichen beinhalten oder nicht als string definiert waren.
#Es wird jeweils eine entsprechende Fehlermeldung ausgegeben.
#Die Codeausführung wird durch einen Error nicht unterbrochen. 

print(type(clean_price(int(6))))

<class 'float'>

In [162]:
#Aufgabe 1_3
#Funktion wird definiert, um string-Einträge in numbers-Einträge umzuwandeln.
def clean_price(price_str):
    """Diese Funktion wandelt string in numeric um."""

    if pd.isna(price_str):
        return np.nan
    price_str_clean = str(price_str).replace("$", "").replace(',', '')
    try:
        price_number = float(price_str_clean)
        if price_number > 0:
            return price_number
        else:
            return np.nan
    except ValueError:
        return np.nan
#Nun wenden wir es auf die gesamte Spalte "price" an.
listings_1_3 = listings.copy()
listings_1_3["price"] = listings_1_3["price"].apply(clean_price)
listings_1_3["price"].describe().loc[['min', '50%', 'mean', 'max']]

min         5.000000
50%       104.000000
mean      201.240393
max     50000.000000
Name: price, dtype: float64

In [163]:
#Aufgabe 1.4_1
listings_1_4 = listings.copy()
#Zunächst schauen wir, welche einzigartigen Einträge es gibt.
listings_1_4["bathrooms_text"].unique()

<StringArray>
[           '1 bath',         '2.5 baths',           '2 baths',
     '1 shared bath',  '1.5 shared baths',         '1.5 baths',
    '1 private bath',    '0 shared baths',    '2 shared baths',
           '0 baths',                 nan,           '3 baths',
  'Shared half-bath',         '4.5 baths',         'Half-bath',
 'Private half-bath',           '8 baths',         '3.5 baths',
  '2.5 shared baths',           '5 baths',         '8.5 baths',
    '4 shared baths',    '3 shared baths',           '4 baths',
  '8.5 shared baths',           '6 baths',          '15 baths',
    '8 shared baths']
Length: 28, dtype: str

In [ ]:
#Aufgabe 1.4_2
#Wir wollen nun die Textdarstellung der Bädersituationen umwandeln in eine numerische Form.
#Regel 1: Die Spezifikation eines "Privaten" Bades ist redundant.
#Regel 2: Die Information eines "Shared" Bades wird durch eine neue boolean-Spalte "Shared_bath_status" erhalten.
#Regel 3: Ein "Half"-Bad gilt als 0.5 Bad.

#Umsetzung Regel 2:
listings_1_4["Shared_bath_status"] = listings_1_4["bathrooms_text"].str.contains("shared", case=False)
#Umsetzung Regel 3:
listings_1_4["bathrooms_text"] = listings_1_4["bathrooms_text"].str.replace("Half-Bath", "0.5", case=False)
#Umsetzung der Umwandlung zu Numerisch unter Beachtung der Regel 1:
listings_1_4["bathrooms_text"] = pd.to_numeric(
    listings_1_4["bathrooms_text"].str.replace({
    "baths": "",
    "shared": "",
    "private": "",
    "bath": "",
    " ": ""
    }, case=False)
)

<class 'numpy.float64'>