In [8]:
#Aufgabe 1.1.
import numpy as np
import pandas as pd

listings = pd.read_csv("Daten/listings_berlin.csv")

print(f"Anzahl Zeilen: {len(listings)} \nAnzahl Spalten: {len(listings.columns)}")

Anzahl_NAs = listings.isna().sum()
Anteil_NAs = listings.isna().mean().map("{:.2%}".format)

df_1_1 = pd.DataFrame({"Anzahl NAs":Anzahl_NAs, "Anteil NAs":Anteil_NAs})
df_1_1.head(20)

Anzahl Zeilen: 14274
Anzahl Spalten: 20

                           Anzahl NAs Anteil NAs
price                            5010     35.10%
neighbourhood_cleansed              0      0.00%
latitude                            0      0.00%
longitude                           0      0.00%
room_type                           0      0.00%
bedrooms                         2024     14.18%
bathrooms_text                     16      0.11%
accommodates                        0      0.00%
amenities                           0      0.00%
host_since                         14      0.10%
host_is_superhost                 164      1.15%
host_listings_count                14      0.10%
host_response_rate               5018     35.15%
review_scores_rating             3314     23.22%
review_scores_cleanliness        3314     23.22%
number_of_reviews                   0      0.00%
reviews_per_month                3314     23.22%
minimum_nights                      0      0.00%
availability_365                    0      0.00%
instant_bookable                    0      0.00%

In [15]:
#Aufagbe 1.2
#Die Tabelle aus Aufgabe 1_1 wird nach den Werten in Spalte "Anteil NAs" in "descending"-order sortiert. 
#Es werden nur die obersten drei Werte angezeigt. 
print("Die folgenden drei Werte haben die höchste Rate an fehlenden Werten:")
df_1_1.sort_values("Anteil NAs", ascending=False).head(3)

Die folgenden drei Werte haben die höchste Rate an fehlenden Werten:

                    Anzahl NAs Anteil NAs
host_response_rate        5018     35.15%
price                     5010     35.10%
reviews_per_month         3314     23.22%

placeholder für den Rest von Aufgabe 1_2

In [ ]:
#Aufgabe 1_3